--관리자 테이블 생성==============================================================================
CREATE TABLE ADMIN(
  ADMIN_NO NUMBER NOT NULL,
  ADMIN_EMAIL VARCHAR2(100) NOT NULL,
  ADMIN_PW VARCHAR2(100) NOT NULL,
  ADMIN_NAME VARCHAR2(50) NOT NULL
);

ALTER TABLE ADMIN 
ADD CONSTRAINT ADMIN_NO_PK 
PRIMARY KEY(ADMIN_NO);

CREATE SEQUENCE ADMIN_NO_SEQ
INCREMENT BY 1
START WITH 1;

INSERT INTO ADMIN
VALUE( ADMIN_NO, ADMIN_EMAIL, ADMIN_PW, ADMIN_NAME)
VALUES(ADMIN_NO_SEQ.NEXTVAL, 'KBG@jbsm.com', '1234', '김보근');

-- 공지사항 테이블 생성=========================================================================
CREATE TABLE NOTICE(
  NOTICE_NO NUMBER NOT NULL,
  NOTICE_TITLE VARCHAR2(100) NOT NULL,
  NOTICE_CONTENT VARCHAR2(1000) NOT NULL,
  NOTICE_CDATE DATE NOT NULL
);

ALTER TABLE NOTICE 
ADD CONSTRAINT NOTICE_NO_PK 
PRIMARY KEY(NOTICE_NO);

CREATE SEQUENCE NOTICE_NO_SEQ
INCREMENT BY 1
START WITH 1;

INSERT INTO NOTICE
VALUE( NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CDATE)
VALUES(NOTICE_NO_SEQ.NEXTVAL, '진보상무에 오신것을 환영합니다', '팀원 김보근, 김진우, 이상현, 조무연 기릿', 
SYSDATE);

INSERT INTO NOTICE
VALUE( NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CDATE)
VALUES(NOTICE_NO_SEQ.NEXTVAL, '발전하는 진보상무', '앞으로 더 발전하는 진보상무가 되겠습니다!', 
SYSDATE);

INSERT INTO NOTICE
VALUE( NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_CDATE)
VALUES(NOTICE_NO_SEQ.NEXTVAL, '기대에 부응하는 진보상무', '모든 고객님들의 기대에 보답하겠습니다!', 
SYSDATE);

--멤버 테이블 생성==============================================================================
CREATE TABLE MEMBER(
  MEMBER_NO NUMBER NOT NULL,
  MEMBER_EMAIL VARCHAR2(100) NOT NULL,
  MEMBER_PW VARCHAR2(100) NOT NULL,
  MEMBER_NAME VARCHAR2(50) NOT NULL,
  MEMBER_PHONE VARCHAR2(20) NOT NULL,
  MEMBER_ZIP VARCHAR2(10) NOT NULL,
  MEMBER_ADDR1 VARCHAR2(200) NOT NULL,
  MEMBER_ADDR2 VARCHAR2(200) NOT NULL,
  MEMBER_CDATE DATE NOT NULL
);

ALTER TABLE MEMBER 
ADD CONSTRAINT MEMBER_NO_PK 
PRIMARY KEY(MEMBER_NO);

ALTER TABLE MEMBER 
ADD CONSTRAINT MEMBER_EMAIL_UK
UNIQUE(MEMBER_EMAIL);

CREATE SEQUENCE MEMBER_NO_SEQ
INCREMENT BY 1
START WITH 1;

--고객센터 테이블 생성=============================================================================
CREATE TABLE CUSTOMER(
  CUSTOMER_NO NUMBER NOT NULL,
  CUSTOMER_MNO NUMBER NOT NULL,
  CUSTOMER_QUE VARCHAR2(1000) NOT NULL,
  CUSTOMER_ANS VARCHAR2(1000),
  CUSTOMER_QDATE DATE NOT NULL,
  CUSTOMER_ADATE DATE
);

ALTER TABLE CUSTOMER 
ADD CONSTRAINT CUSTOMER_NO_PK 
PRIMARY KEY(CUSTOMER_NO);

ALTER TABLE CUSTOMER
ADD CONSTRAINT CUSTOMER_MNO_FK
FOREIGN KEY(CUSTOMER_MNO) REFERENCES MEMBER (MEMBER_NO);

CREATE SEQUENCE CUSTOMER_NO_SEQ
INCREMENT BY 1
START WITH 1;

--이벤트 테이블 생성===============================================================================
CREATE TABLE EVENT(
  EVENT_NO NUMBER NOT NULL,
  EVENT_NAME VARCHAR2(100) NOT NULL,
  EVENT_TIMG VARCHAR2(100) NOT NULL,
  EVENT_DIMG VARCHAR2(100) NOT NULL,
  EVENT_SDATE VARCHAR2(10) NOT NULL,
  EVENT_EDATE VARCHAR2(10) NOT NULL
);

ALTER TABLE EVENT 
ADD CONSTRAINT EVENT_NO_PK 
PRIMARY KEY(EVENT_NO);

CREATE SEQUENCE EVENT_NO_SEQ
INCREMENT BY 1
START WITH 1;

COMMIT;